apiVersion : apps/v1
kind: Deployment
metadata:
  name: "recogaks-front"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "recogaks-front"
  template:
    metadata:
      labels:
        app: "recogaks-front"
    spec:
      containers:
        - name: "recogaks-front"
          image: "recogacr.azurecr.io/recogaks"
          ports:
          - containerPort: 3000