apiVersion: v1
kind: Service
metadata:
    name: "akscluster-e2e5"
    labels:
        app: "akscluster-e2e5"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "akscluster-e2e5"