apiVersion: v1
kind: Service
metadata:
    name: "recogaks-front"
    labels:
        app: "recogaks-front"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "recogaks-front"