import Head from "next/head";
import Image from "next/image";
import MediaOptions from "../components/MediaOptions";
import PhotoMedia from "../components/PhotoMedia";
import ProtoTxtEditor from "../components/ProtoTxtEditor";
import VideoStream from "../components/VideoStream";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MediaOptions></MediaOptions>
        <ProtoTxtEditor></ProtoTxtEditor>
        <PhotoMedia></PhotoMedia>
        <VideoStream></VideoStream>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
